version: 2.1

orbs:
  node: circleci/node@3.0.0

jobs:
  run-tests:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run: # run tests
          name: Run Test and Coverage
          command: |
            npm test -- --coverage

workflows:
  build-and-test:
    jobs:
      - run-tests

